services:
  user:
    build:
      context: .
      dockerfile: apps/user/Dockerfile
    env_file:
      - apps/user/.env.docker
    ports:
      - "3002:3002"
    depends_on:
      - mysql-user
      - rabbitmq

  mysql-user:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task
    volumes:
      - user-mysql-data:/var/lib/mysql

  auth:
  build:
    context: .
    dockerfile: apps/auth/Dockerfile
  env_file:
    - apps/auth/.env.docker
  ports:
    - "3001:3001"
  depends_on:
    - mysql-auth
    - rabbitmq

  mysql-auth:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task
    volumes:
      - auth-mysql-data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  user-mysql-data:
  auth-mysql-data: